apiVersion: apps/v1
kind: Deployment
metadata:
  name: Sales
  labels:
    app: Sales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Sales
  template:
    metadata:
      labels:
        app: Sales
    spec:
      containers:
        - name: Sales
          image: username/Sales:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5